### PR TITLE
Allow "Symfony Filesystem" 7.x

### PR DESCRIPTION
**Pull request by jackrabbithanna**
Drupal 11 requires Symfony 7.

Update composer.json to allow Symfony 7

### CODE REVIEW

**Comment by totten** [comment]
@jackrabbithanna I think this may need a rebase to trigger new test-run with the updated actions (#7).

**Comment by jackrabbithanna** [comment]
@totten done. I synced my fork's master branch, and merged master into this feature branch, tests running again.

**Comment by totten** [comment]
Thanks @jackrabbithanna. Looks like the new test run is clean. ✅ 

Also, the [changelog for symfony/filesystem@7](https://github.com/symfony/filesystem/blob/7.0/CHANGELOG.md) looks quite innocuous. ✅

**Comment by totten** [comment]
Merged and tagged as v0.8.

**Pull request merged**
