### PR TITLE
Update SCSS Compiler to work with later versions of scssphp/scssphp

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @mikeymjco

```
> @php -r "require_once '.../vendor/autoload.php'; Civi\CompilePlugin\TaskTransfer::import(); \CCL::copy('../../bower_components/select2/select2-bootstrap.css', 'extern/select2/select2-bootstrap.scss');"
> @php -r "require_once '.../vendor/autoload.php'; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::scss($GLOBALS[ COMPOSER_COMPILE_TASK ]);"
PHP Warning:  Use of undefined constant COMPOSER_COMPILE_TASK - assumed 'COMPOSER_COMPILE_TASK' (this will throw an Error in a future version of PHP) in Command line code on line 1
PHP Warning:  Declaration of CCL\ScssCompiler::findImport($url) should be compatible with ScssPhp\ScssPhp\Compiler::findImport($url, $currentDir = NULL) in ...\vendor\civicrm\composer-compile-lib\src\ScssCompiler.php on line 17
PHP Fatal error:  Uncaught ScssPhp\ScssPhp\Exception\CompilerException: `mixins/hide-text` file not found for @import: extern/bootstrap3/assets/stylesheets\bootstrap/_mixins.scss on line 5, at column 1
Call Stack:
0 import extern/bootstrap3/assets/stylesheets\bootstrap/_mixins.scss extern/bootstrap3/assets/stylesheets/_bootstrap.scss on line 9
1 import extern/bootstrap3/assets/stylesheets/_bootstrap.scss (unknown file) on line 3 in ...\vendor\scssphp\scssphp\src\Compiler.php:5960
Stack trace:
0 ...\vendor\scssphp\scssphp\src\Compiler.php(5733): ScssPhp\ScssPhp\Compiler->error('`mixins/hide-te...')
1 ...\vendor\civicrm\composer-compile-lib\src\ScssCompiler.php(45): ScssPhp\ScssPhp\Compiler->findImport('mixins/hide-tex...')
2 ...\vendor\scssphp\scssphp\src\Compiler.php(2644): CCL\ScssCompiler->findImport('mixins/hide-tex...', 'extern/bootstra...')
3  in ...\vendor\scssphp\scssphp\src\Compiler.php on line 5960
Script @php -r "require_once '.../vendor/autoload.php'; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::scss($GLOBALS[ COMPOSER_COMPILE_TASK ]);" handling the shell-runner event returned with error code 255

Warning: Use of undefined constant COMPOSER_COMPILE_TASK - assumed 'COMPOSER_COMPILE_TASK' (this will throw an Error in a future version of PHP) in Command line code on line 1

Warning: Declaration of CCL\ScssCompiler::findImport($url) should be compatible with ScssPhp\ScssPhp\Compiler::findImport($url, $currentDir = NULL) in ...\vendor\civicrm\composer-compile-lib\src\ScssCompiler.php on line 17

Fatal error: Uncaught ScssPhp\ScssPhp\Exception\CompilerException: `mixins/hide-text` file not found for @import: extern/bootstrap3/assets/stylesheets\bootstrap/_mixins.scss on line 5, at column 1
Call Stack:
0 import extern/bootstrap3/assets/stylesheets\bootstrap/_mixins.scss extern/bootstrap3/assets/stylesheets/_bootstrap.scss on line 9
1 import extern/bootstrap3/assets/stylesheets/_bootstrap.scss (unknown file) on line 3 in ...\vendor\scssphp\scssphp\src\Compiler.php:5960
Stack trace:
0 ...\vendor\scssphp\scssphp\src\Compiler.php(5733): ScssPhp\ScssPhp\Compiler->error('`mixins/hide-te...')
1 ...\vendor\civicrm\composer-compile-lib\src\ScssCompiler.php(45): ScssPhp\ScssPhp\Compiler->findImport('mixins/hide-tex...')
2 ...\vendor\scssphp\scssphp\src\Compiler.php(2644): CCL\ScssCompiler->findImport('mixins/hide-tex...', 'extern/bootstra...')
3  in ...\vendor\scssphp\scssphp\src\Compiler.php on line 5960
Subcommand @composer compile  returned with error code 255

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### CODE REVIEW

**Comment by totten** [comment]
@seamuslee001 I was just about to point out the bits that you pushed in 1122006 :) With that, I think it makes sense.

Full disclosure - it may be possible to support 1.2 and 1.5 simultaneously. Note PHP's mechanics on how base-classes and sub-classes interact: https://gist.github.com/totten/6d5734576159efa19de6dd57580d3c77

The only reason one might do that -- is if we thought that downstream admins would get boxed-in somehow by precluding older versions of `scssphp`. Of course, from a dev POV, it's easier to grok things if we just raise the minimum requirement for `scssphp`.

**Comment by demeritcowboy** [comment]
Commenting that I tested this and it fixes the error. I had to rerun `composer civicrm:publish` afterwards to get my menus back but that might be because of the original failure.

**Comment by homotechsual** [comment]
Looks good to me too!

**Comment by totten** [comment]
Merging based on `r-run` comments from above.

For the record... if folks do get version-conflicts from this (e.g. they need `scssphp` 1.2/1.3/1.4 for some other reason), then I'd suggest directly applying the patch for `src/ScssCompiler.php` or trying an `as` requirement (IIRC, `composer require some/pkg:'1.4.0 as 1.5.1'`). In theory, this patch for `src/ScssCompiler.php` would be valid when mixed with newer-or-older versions of `scssphp`. If someone `r-run`s the patch successfully on an older version, then we could relax the `composer.json` requirement here (and make the upgrade-experience more forgiving).

**Pull request merged**
